### ISSUE TITLE
Interested in an implementation that uses GDScript?

### ISSUE THREAD

**Issue by IAmBaguette** [Hyrdaboo/TrailRenderer#1]
Hi,

I really appreciate the effort that was put into this addon.

I'm not sure about the level of interest in a GDScript (Godot 4.x) implementation of this addon. That said, I'd like to share my implementation: [Gist TrailRenderer-GDScript](https://gist.github.com/IAmBaguette/47274266afb685232a537b04424727ac)

EDIT: Fixed broken link.

**Comment by Hyrdaboo** [comment]
@IAmBaguette Hi, the link you provided does not work for some reason. If you want contribute to this repo by adding a GDScript implementation you are welcome to do so. I will review your additions and if everything works as expected merge them.

**Comment by IAmBaguette** [comment]
@Hyrdaboo Sorry about that. I have updated the link and it should now work correctly.

Is there any particular folder you would like me to place it in? I split the classes into their own individual files (4).

**Comment by Hyrdaboo** [comment]
@IAmBaguette Hi, addons/TrailRenderer/Runtime/GD would be nice. You can fork this repo and add your files to said directory then go ahead and make a pull request so I can approve them. Here's [an article](https://opensource.com/article/19/7/create-pull-request-github) just in case you don't know how to do that.

**Comment by IAmBaguette** [comment]
@Hyrdaboo Thanks for the guidance. I have created the pull request: https://github.com/Hyrdaboo/TrailRenderer/pull/2

**Comment by Hyrdaboo** [comment]
@IAmBaguette Tested it and everything seems to be working fine. Good job👍
